DDACMaerskCMS/Controllers/ContainersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DDACMaerskCMS.Models;

namespace DDACMaerskCMS.Controllers
{
    public class ContainersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Containers
        public ActionResult Index()
        {
            return View(db.Containers.ToList());
        }

        // GET: Containers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Container container = db.Containers.Find(id);
            if (container == null)
            {
                return HttpNotFound();
            }
            return View(container);
        }

        // GET: Containers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Containers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        
        public ActionResult Create([Bind(Include = "ContainerID,ContainerDescription,ContainerWeight")] Container container)
        {
            if (ModelState.IsValid)
            {
                db.Containers.Add(container);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(container);
        }

        // GET: Containers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Container container = db.Containers.Find(id);
            if (container == null)
            {
                return HttpNotFound();
            }
            return View(container);
        }

        // POST: Containers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        
        public ActionResult Edit([Bind(Include = "ContainerID,ContainerDescription,ContainerWeight")] Container container)
        {
            if (ModelState.IsValid)
            {
                db.Entry(container).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(container);
        }

        // GET: Containers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Container container = db.Containers.Find(id);
            if (container == null)
            {
                return HttpNotFound();
            }
            return View(container);
        }

        // POST: Containers/Delete/5
        [HttpPost, ActionName("Delete")]
        
        public ActionResult DeleteConfirmed(int id)
        {
            Container container = db.Containers.Find(id);
            db.Containers.Remove(container);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DDACMaerskCMS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DDACMaerskCMS.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DDACMaerskCMS/Controllers/ShipsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DDACMaerskCMS.Models;

namespace DDACMaerskCMS.Controllers
{
    public class ShipsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Ships
        public ActionResult Index()
        {
            return View(db.Ships.ToList());
        }

        // GET: Ships/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ship ship = db.Ships.Find(id);
            if (ship == null)
            {
                return HttpNotFound();
            }
            return View(ship);
        }

        // GET: Ships/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ships/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        
        public ActionResult Create([Bind(Include = "ShipID,ShipName,ShipType,ShipWeight,TotalContainers")] Ship ship)
        {
            if (ModelState.IsValid)
            {
                db.Ships.Add(ship);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ship);
        }

        // GET: Ships/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ship ship = db.Ships.Find(id);
            if (ship == null)
            {
                return HttpNotFound();
            }
            return View(ship);
        }

        // POST: Ships/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        
        public ActionResult Edit([Bind(Include = "ShipID,ShipName,ShipType,ShipWeight,TotalContainers")] Ship ship)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ship).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ship);
        }

        // GET: Ships/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ship ship = db.Ships.Find(id);
            if (ship == null)
            {
                return HttpNotFound();
            }
            return View(ship);
        }

        // POST: Ships/Delete/5
        [HttpPost, ActionName("Delete")]
        
        public ActionResult DeleteConfirmed(int id)
        {
            Ship ship = db.Ships.Find(id);
            db.Ships.Remove(ship);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DDACMaerskCMS/Controllers/YardLocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DDACMaerskCMS.Models;

namespace DDACMaerskCMS.Controllers
{
    public class YardLocationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: YardLocations
        public ActionResult Index()
        {
            return View(db.YardLocations.ToList());
        }

        // GET: YardLocations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            YardLocation yardLocation = db.YardLocations.Find(id);
            if (yardLocation == null)
            {
                return HttpNotFound();
            }
            return View(yardLocation);
        }

        // GET: YardLocations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: YardLocations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        
        public ActionResult Create([Bind(Include = "YardLocationID,YardName,LocationName,CountryName")] YardLocation yardLocation)
        {
            if (ModelState.IsValid)
            {
                db.YardLocations.Add(yardLocation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(yardLocation);
        }

        // GET: YardLocations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            YardLocation yardLocation = db.YardLocations.Find(id);
            if (yardLocation == null)
            {
                return HttpNotFound();
            }
            return View(yardLocation);
        }

        // POST: YardLocations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        
        public ActionResult Edit([Bind(Include = "YardLocationID,YardName,LocationName,CountryName")] YardLocation yardLocation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(yardLocation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(yardLocation);
        }

        // GET: YardLocations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            YardLocation yardLocation = db.YardLocations.Find(id);
            if (yardLocation == null)
            {
                return HttpNotFound();
            }
            return View(yardLocation);
        }

        // POST: YardLocations/Delete/5
        [HttpPost, ActionName("Delete")]
        
        public ActionResult DeleteConfirmed(int id)
        {
            YardLocation yardLocation = db.YardLocations.Find(id);
            db.YardLocations.Remove(yardLocation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DDACMaerskCMS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DDACMaerskCMS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DDACMaerskCMS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div style='text-align: center;padding: 30px;margin-bottom: 30px;font-size: 21px;font-weight: 200;line-height: 2.1428571435;'>
    <div style='font-family: "Matura MT Script Capitals";font-weight: 500;font-size: 80px;line-height: 1.1;'>Maersk Line</div><br>
    <div style='font-family: "Matura MT Script Capitals";font-weight: 200;font-size: 45px;line-height: 1.1;'>Container Management System (CMS)</div>
</div>
<br>

<div class="row" style='text-align:center'>
    <div class="col-md-2"></div>
    <div class="col-md-4" style='background-color:floralwhite; opacity:0.9; border:2px solid black; border-radius: 10px; text-align:center'>

        <h2>Ship Details</h2>
        <a href='@Url.Action("Index", "Ships")'>
            <img src='@Url.Content("http://www.freeiconspng.com/uploads/ship-icon--spanish-travel-iconset--unclebob-2.png")' style="width:150px;height:150px;" />
        </a><br><br><br>
    </div>
    <div class="col-md-4" style='background-color:floralwhite; opacity:0.9; border:2px solid black; border-radius: 10px; text-align:center'>

        <h2>Container Details</h2>
        <a href='@Url.Action("Index", "Containers")'>
            <img src='@Url.Content("https://d30y9cdsu7xlg0.cloudfront.net/png/47752-200.png")' style="width:150px;height:150px;" />
        </a><br><br><br>
    </div>
    <div class="col-md-2"></div>
</div>
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-4" style='background-color:floralwhite; opacity:0.9; border:2px solid black; border-radius: 10px; text-align:center'>

        <h2>Yard Details</h2>
        <a href='@Url.Action("Index", "YardLocations")'>
            <img src='@Url.Content("https://openclipart.org/image/800px/svg_to_png/218695/port.png")' style="width:150px;height:150px;" />
        </a><br><br><br>
    </div>
    <div class="col-md-4" style='background-color:floralwhite; opacity:0.9; border:2px solid black; border-radius: 10px; text-align:center'>

        <h2>Shipping Details</h2>
        <a href='@Url.Action("Index", "ContainerShippingSchedules")'>
            <img src='@Url.Content("https://www.tsl.texas.gov/sites/default/files/public/tslac/slrm/landingpage/retentionschedule.png")' style="width:150px;height:150px;" />
        </a><br><br><br>
    </div>
    <div class="col-md-2"></div>
</div>